module.exports = [
  {
    slug: 'yueyang-lou-ji', title: '岳阳楼记', author: '范仲淹', source: 'yueyang.txt', seal: '岳',
    scenes: [
      { id: 'renewal', art: 'yueyang-renewal', label: '重修岳阳楼', position: '60% 50%', mobile: '90% 50%',
        alt: '晨雾中的岳阳楼临洞庭而立，楼下尚有修葺的匠人，湖岸渐渐苏醒。', weather: [.60,0,0],
        paragraphs: ['庆历四年春，滕子京谪守巴陵郡。<br>越明年，政通人和，百废具兴。', '乃重修岳阳楼，增其旧制，<br>刻唐贤今人诗赋于其上。<br>属予作文以记之。'] },
      { id: 'vastness', art: 'yueyang-vastness', label: '衔远山，吞长江', mobile: '75% 50%',
        alt: '洞庭吞纳江流，远山层叠，一叶帆舟显得格外渺小。', weather: [.43,0,0], camera: [1.12,1.025],
        paragraphs: ['予观夫巴陵胜状，在洞庭一湖。', '<span class="spoken">衔远山，吞长江，</span>浩浩汤汤，横无际涯；'] },
      { id: 'changing-light', art: 'yueyang-changing-light', label: '朝晖夕阴', mobile: '100% 50%',
        alt: '洞庭云影与日光交替，岳阳楼的檐角俯瞰远方帆影。', weather: [.54,0,0],
        paragraphs: ['朝晖夕阴，气象万千。<br>此则岳阳楼之大观也，前人之述备矣。', '然则北通巫峡，南极潇湘，<br>迁客骚人，多会于此，<br>览物之情，得无异乎？'] },
      { id: 'storm', art: 'yueyang-storm', label: '阴风怒号，浊浪排空', dark: true, mobile: '100% 50%',
        alt: '风雨封住洞庭的远山，灰黑的巨浪翻涌，天色晦暗。', weather: [.35,.8,0], camera: [1.03,1.085],
        paragraphs: ['若夫淫雨霏霏，连月不开，<br>阴风怒号，浊浪排空，<br>日星隐曜，山岳潜形；'] },
      { id: 'dusk', art: 'yueyang-dusk', label: '薄暮冥冥', dark: true, mobile: '64% 50%',
        alt: '雨暮中停泊的旧船，折断的桨靠在岸边，一盏灯等待归人。', weather: [.62,.35,.10], fire: [.611,.538],
        portal: { to: 'sorrow', point: [.611,.538], label: '点击船灯，走近楼中的独客' },
        paragraphs: ['商旅不行，樯倾楫摧；<br>薄暮冥冥，虎啸猿啼。'] },
      { id: 'sorrow', art: 'yueyang-sorrow', label: '去国怀乡', dark: true, mobile: '75% 50%',
        alt: '一位宋代迁客立在楼窗边，风雨中的洞庭隔开了他与故乡。', weather: [.88,.12,0],
        paragraphs: ['登斯楼也，则有去国怀乡，<br>忧谗畏讥，满目萧然，<br>感极而悲者矣。'] },
      { id: 'spring', art: 'yueyang-spring', label: '春和景明', mobile: '53% 50%',
        alt: '晴春的洞庭碧水连天，沙鸥掠过水面，游鱼的银光隐约可见。', weather: [.44,0,0],
        portal: { to: 'banks', point: [.56,.62], label: '点击近岸的芷兰，走近春水' },
        paragraphs: ['至若春和景明，波澜不惊，<br>上下天光，一碧万顷；<br>沙鸥翔集，锦鳞游泳；'] },
      { id: 'banks', art: 'yueyang-banks', label: '岸芷汀兰', mobile: '71% 50%',
        alt: '近岸香草与兰花生在水边，嫩绿的叶子倒映在清澈春水中。', weather: [.60,-.15,0],
        paragraphs: ['<span class="spoken">岸芷汀兰，<br>郁郁青青。</span>'] },
      { id: 'moon', art: 'yueyang-moon', label: '浮光跃金，静影沉璧', dark: true, mobile: '88% 50%', mobileBottom: true,
        alt: '皓月下的洞庭澄澈辽阔，月影与渔舟的灯火落在湖上。', weather: [.46,0,.085], fire: [.753,.648],
        portal: { to: 'wine', point: [.753,.648], label: '点击渔舟灯火，进入楼中把酒临风的近景' },
        paragraphs: ['而或长烟一空，皓月千里，<br>浮光跃金，静影沉璧，<br>渔歌互答，此乐何极！'] },
      { id: 'wine', art: 'yueyang-wine', label: '把酒临风', dark: true, mobile: '67% 50%',
        alt: '月夜楼栏边，游人迎着湖风举起酒杯，神色开朗而宁静。', weather: [.74,0,.04], fire: [.969,.851],
        portal: { to: 'heart', point: [.547,.457], label: '点击酒杯，进入古仁人之心' },
        paragraphs: ['登斯楼也，则有心旷神怡，<br>宠辱偕忘，把酒临风，<br>其喜洋洋者矣。'] },
      { id: 'heart', art: 'yueyang-heart', label: '不以物喜，不以己悲', dark: true, mobile: '63% 50%', dense: true,
        alt: '静室中的宋代士人面对案卷，窗外遥见田野与百姓，悲喜渐归于沉静。', weather: [.98,0,.07], fire: [.807,.655],
        portal: { to: 'concern', point: [.64,.73], label: '点击案卷，进入范仲淹写作时的心境' },
        paragraphs: ['嗟夫！予尝求古仁人之心，<br>或异二者之为，何哉？', '<span class="spoken">不以物喜，不以己悲；</span>', '居庙堂之高则忧其民；<br>处江湖之远则忧其君。'] },
      { id: 'concern', art: 'yueyang-concern', label: '先忧后乐', dark: true, mobile: '77% 50%', dense: true, distance: 2.25,
        alt: '想象中的范仲淹在邓州灯下执笔，洞庭、田野和行旅化为遥思天下的心境。', weather: [.98,0,.08], fire: [.50,.62],
        paragraphs: ['是进亦忧，退亦忧。<br>然则何时而乐耶？其必曰', '<span class="spoken">“先天下之忧而忧，<br>后天下之乐而乐”乎！</span>', '噫！微斯人，吾谁与归？', '时六年九月十五日。'] }
    ]
  },
  {
    slug: 'zuiweng-ting-ji', title: '醉翁亭记', author: '欧阳修', source: 'zuiweng.txt', seal: '醉',
    scenes: [
      { id: 'mountains', art: 'zuiweng-mountains', label: '环滁皆山', mobile: '67% 50%', weather: [.98,-.12,0],
        alt: '琅琊群峰环绕滁州，青翠的林壑一层层隐入晨雾。',
        paragraphs: ['环滁皆山也。其西南诸峰，林壑尤美，<br>望之蔚然而深秀者，琅琊也。'] },
      { id: 'spring', art: 'zuiweng-spring', label: '酿泉', mobile: '78% 50%', weather: [.51,-.10,0],
        alt: '酿泉从两峰间的青苔山石流出，清流环过树根与白花。',
        portal: { to: 'pavilion', point: [.705,.64], label: '点击泉水，随山路走近醉翁亭' },
        paragraphs: ['山行六七里，渐闻水声潺潺，<br>而泻出于两峰之间者，酿泉也。'] },
      { id: 'pavilion', art: 'zuiweng-pavilion', label: '有亭翼然', mobile: '70% 50%', weather: [.78,-.08,0],
        alt: '峰回路转，醉翁亭的檐角如飞翼伸向泉水，几位游人刚刚入亭。',
        paragraphs: ['峰回路转，有亭翼然临于泉上者，<br>醉翁亭也。', '作亭者谁？山之僧智仙也。<br>名之者谁？太守自谓也。'] },
      { id: 'intention', art: 'zuiweng-intention', label: '醉翁之意', mobile: '70% 50%', weather: [.98,-.07,0],
        alt: '欧阳修与客人坐在亭内，手边一杯淡酒，目光却向着青山泉水。',
        paragraphs: ['太守与客来饮于此，饮少辄醉，<br>而年又最高，故自号曰醉翁也。', '<span class="spoken">醉翁之意不在酒，<br>在乎山水之间也。</span>', '山水之乐，得之心而寓之酒也。'] },
      { id: 'daylight', art: 'zuiweng-daylight', label: '山间朝暮', mobile: '70% 50%', weather: [.96,-.15,0],
        alt: '山林中的晨光穿开轻雾，远处岩穴仍在幽暗之中，明暗交错。',
        paragraphs: ['若夫日出而林霏开，云归而岩穴暝，<br>晦明变化者，山间之朝暮也。'] },
      { id: 'seasons', art: 'zuiweng-seasons', label: '山间四时', mobile: '57% 50%', weather: [.65,-.20,0], dense: true,
        alt: '同一片山林的四时意象：野花、浓荫、秋霜与清浅露石的溪水，融为连续山景。',
        paragraphs: ['野芳发而幽香，佳木秀而繁阴，<br>风霜高洁，水落而石出者，<br>山间之四时也。', '朝而往，暮而归，四时之景不同，<br>而乐亦无穷也。'] },
      { id: 'people', art: 'zuiweng-people', label: '滁人游', mobile: '75% 50%', weather: [.98,-.15,0],
        alt: '山路上，负担的乡人、扶杖的老人和牵手的孩子往来相呼，树下有人歇脚。',
        paragraphs: ['至于负者歌于途，行者休于树，<br>前者呼，后者应，伛偻提携，<br>往来而不绝者，滁人游也。'] },
      { id: 'banquet', art: 'zuiweng-banquet', label: '太守宴', mobile: '78% 50%', weather: [.98,0,0],
        alt: '亭下的木案摆着溪鱼、野菜、山果和清酒，宾客围坐在朴素的山宴旁。',
        portal: { to: 'guests', point: [.697,.70], label: '点击山宴中的酒壶，走近众宾欢聚' },
        paragraphs: ['临溪而渔，溪深而鱼肥，<br>酿泉为酒，泉香而酒洌，<br>山肴野蔌，杂然而前陈者，太守宴也。'] },
      { id: 'guests', art: 'zuiweng-guests', label: '众宾欢', mobile: '62% 50%', weather: [.98,-.04,0],
        alt: '山亭里有人投壶，有人弈棋，有人举杯，宾客相笑，气氛亲切热闹。',
        portal: { to: 'drunk', point: [.533,.451], label: '点击举起的酒杯，走近醉翁' },
        paragraphs: ['宴酣之乐，非丝非竹，<br>射者中，弈者胜，觥筹交错，<br>起坐而喧哗者，众宾欢也。'] },
      { id: 'drunk', art: 'zuiweng-drunk', label: '太守醉', mobile: '62% 50%', weather: [.98,-.04,0],
        alt: '苍颜白发的醉翁倚着亭柱，衣袖松落，宾客的笑影在身后，面容安然。',
        paragraphs: ['<span class="spoken">苍颜白发，颓然乎其间者，<br>太守醉也。</span>'] },
      { id: 'return', art: 'zuiweng-return', label: '夕阳在山', dark: true, mobile: '75% 50%', weather: [.98,-.18,.07],
        alt: '夕阳下太守与宾客沿山路归去，树冠的鸟影重新聚拢，林间渐渐宁静。',
        portal: { to: 'writing', point: [.685,.625], label: '点击归途中的灯火，进入欧阳修写作时的心境' }, fire: [.685,.625],
        paragraphs: ['已而夕阳在山，人影散乱，<br>太守归而宾客从也。', '树林阴翳，鸣声上下，<br>游人去而禽鸟乐也。'] },
      { id: 'writing', art: 'zuiweng-writing', label: '醉能同其乐，醒能述以文', dark: true, mobile: '72% 50%', weather: [.98,0,.07], fire: [.447,.680], dense: true, distance: 2.35,
        alt: '想象中的欧阳修在灯下展纸执笔，山林与游人欢聚的记忆映在窗外，神色温和。',
        paragraphs: ['然而禽鸟知山林之乐，而不知人之乐；<br>人知从太守游而乐，<br>而不知太守之乐其乐也。', '醉能同其乐，醒能述以文者，<br>太守也。', '<span class="spoken">太守谓谁？<br>庐陵欧阳修也。</span>'] }
    ]
  }
];
